AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - client/**/*
    - node_modules/
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Metrics/ParameterLists:
  CountKeywordArgs: false
Style/Lambda:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/WordArray:
  Enabled: false
Style/FormatStringToken:
  EnforcedStyle: template
inherit_from: .rubocop_todo.yml
